#logging:
#  level:
#    org:
#      springframework: debug
server:
  port: 8800

spring:
  application:
    name: product-micro-service
  active:
    profile: local-discovery
  datasource:
    url: jdbc:mysql://localhost:3306/elevatemart
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    jdbc:
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

file:
  upload-dir: src/main/resources/fileImages

jwt:
  security:
    token:
      secret_key: abMcdefgIhijk4lmnoXpqrsZtuvwxyzYafeA
      issuer: ashoaib.security@gmail.com
      subject: emartSalesPlatform@gmail.com
      earlierBefore: 300